//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "message_link")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub message_parent_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub message_child_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::messages::Entity",
        from = "Column::MessageChildId",
        to = "super::messages::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Messages2,
    #[sea_orm(
        belongs_to = "super::messages::Entity",
        from = "Column::MessageParentId",
        to = "super::messages::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Messages1,
}

impl ActiveModelBehavior for ActiveModel {}
