//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20


pub use super::channels::Entity as Channels;
pub use super::messages::Entity as Messages;
pub use super::servers::Entity as Servers;
pub use super::users::Entity as Users;