//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "servers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTime,
    pub changed_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::servers_users::Entity")]
    ServersUsers,
}

impl Related<super::servers_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServersUsers.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::servers_users::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::servers_users::Relation::Servers.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
