name: Rust CI/CD (Windows Self-hosted)

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure Rust is installed
        shell: powershell
        run: |
          if (!(Get-Command rustc -ErrorAction SilentlyContinue)) {
            Write-Host "Installing Rust..."
            Invoke-WebRequest https://win.rustup.rs/x86_64 -OutFile rustup-init.exe
            Start-Process .\rustup-init.exe -ArgumentList "-y" -Wait
          }

      - name: Install components (rustfmt + clippy)
        shell: powershell
        run: |
          rustup component add rustfmt
          rustup component add clippy

      - name: Cache cargo registry + build
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\${{ github.actor }}\.cargo\registry
            C:\Users\${{ github.actor }}\.cargo\git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # - name: Format check
      #   shell: powershell
      #   run: cargo fmt -- --check

      - name: Clippy (lint)
        shell: powershell
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        shell: powershell
        run: cargo build --verbose

      - name: Test
        shell: powershell
        run: cargo test --verbose


  release:
    runs-on: self-hosted
    needs: ci
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build release
        shell: powershell
        run: cargo build --release

      - name: Get binary name
        id: bin
        shell: powershell
        run: |
          $name = (Get-Content Cargo.toml | Select-String 'name =').ToString().Split('"')[1]
          echo "name=$name.exe" >> $env:GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-binary
          path: target/release/${{ steps.bin.outputs.name }}
